### ISSUE TITLE
The ਉ and ੱ may be too close to each other.

### ISSUE THREAD

**Issue by dsomel21** [shabados/SantLipi#31]
## Description

I've been testing Sant Lipi v0.011 on a local instance of the [SPG website](https://spg.dev/books) with lines from Nanak Prakash.

This is happening on ALL font-weights. In the fatter font-weights, it's even MORE apparent.

## Example Text

> ਉੱਤਰ ਆਵ ਨ ਉਠਿ ਘਰ ਗਯੋ।

## Images

<img src="https://user-images.githubusercontent.com/17516559/219958922-639c6cdd-c402-41c6-a767-788e5dce2171.png" width="756" />

### Environment

MacOS 10.15.7, Chrome 110.0.5481.100 (Official Build) (x86_64)

**Comment by bhajneet** [comment]
Related #28
