### ISSUE TITLE
Investigate alignment issues

### ISSUE THREAD

**Issue by bhajneet** [shabados/SantLipi#33]
### Investigation

The mark attachments are correctly placed in Glyphs3 and doesn't show up in the preview tool there

![image](https://user-images.githubusercontent.com/14130567/219960819-bbd1db23-3e81-44a3-92ed-d87e7a33515b.png)

Need to reproduce this

### Timebox

1 day

### Outcome

- asdf

**Comment by bhajneet** [comment]
@dsomel21 I can't seem to reproduce this on the Test Suite: https://shabados.github.io/SantLipi/qa/test/spg.html

Can you help me figure out what you did to display this?

**Comment by dsomel21** [comment]
Are you still getting alignment issues?

I checked it as well, I still see it on the live testing site. 

<img width="935" alt="Screen Shot 2023-02-19 at 12 43 16 PM" src="https://user-images.githubusercontent.com/17516559/219965586-709879eb-d733-41eb-a0ae-1fd62a2b328a.png">

**Comment by dsomel21** [comment]
<img width="1085" alt="Screen Shot 2023-02-19 at 1 09 07 PM" src="https://user-images.githubusercontent.com/17516559/219966763-df212d26-0273-414b-b93f-3a0354f75b05.png">

**Comment by bhajneet** [comment]
Interesting! What zoom level are you using? What's your browser?

**Comment by dsomel21** [comment]
This is me using it at 175% zoom. You can see it a "bit"


<img width="1126" alt="Screen Shot 2023-02-19 at 7 41 16 PM" src="https://user-images.githubusercontent.com/17516559/219985839-428f81d8-9f34-44f6-acf5-ff59d9415394.png">

**Comment by bhajneet** [comment]
This is my chrome browser at 500% on macOS

<img width="751" alt="image" src="https://user-images.githubusercontent.com/14130567/219987166-7d750231-6b7a-4e61-a88b-a7df18600872.png">

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/14130567/219987209-200ab765-64ce-4d80-a0c6-ee30c2f3e827.png">

**Comment by bhajneet** [comment]
Could it be the colors? Can you send me them so I can test that?

**Comment by dsomel21** [comment]
This is what we use for (Dark Mode). 

{
    color: #f7ebd4;
    background: 2D2D2F;
}

**Comment by bhajneet** [comment]
Looks like it's a font weight thing:

https://user-images.githubusercontent.com/14130567/220144018-84352446-ae83-4710-bfed-484547aa255e.mov

**Comment by dsomel21** [comment]
Amazing!
