### ISSUE TITLE
Add special chars for Mahan Kosh

### ISSUE THREAD

**Issue by dsomel21** [shabados/SantLipi#41]
### Summary

(More of a note for myself). 

## Description 

[Reference](https://www.srigranth.org/servlet/gurbani.dictionary?Param=%E0%A8%A8%E0%A8%95%E0%A9%8D%E0%A8%B6%E0%A8%A4%E0%A9%8D%E0%A8%B0) in Mahan Kosh.

Is that thing under the Kakka corect? This is what it looks like in Sant Lipi:

<img width="572" alt="Screen Shot 2023-04-24 at 11 24 02 PM" src="https://user-images.githubusercontent.com/17516559/234167051-53626c37-f691-4f9d-9d63-07e6554d4210.png">

### Approach

-

**Comment by dsomel21** [comment]
Hmmmm, I have the Mahan Kosh book. Idk where I can find it handwritten 🫤

**Comment by dsomel21** [comment]
I found it. I don't have a camera on me, but it basically looks like a Kakka with a line through the bottom hole. 

Kinda like this:

<img width="1113" alt="Screen Shot 2023-04-25 at 9 21 04 AM" src="https://user-images.githubusercontent.com/17516559/234290225-561418e6-7146-4297-b6fa-b06e0cfcdf3e.png">

**Comment by bhajneet** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/14130567/234413746-8965a06e-6eeb-4a11-9d2d-01c5213f17e2.png">


What you're referencing is a special character used in Mahan Kosh. It will be added later. I'm going to update this issue for that.

**Comment by bhajneet** [comment]
Notes (going down column 1)

Even though Devanagari and Gurmukhi both stem from Brahma/Gupta scripts, text rendering engines will not allow gurmukhi vowels on devanagari code points. So can't just style gurmukhi letters on the devanagari unicode points unless they are being used as is (without vowel modification). Others which can fit into Gurmukhi without issue can just be added as is (e.g. half-m and r w/ nukta).

- Half s (typed as स् + char)
- ṣ, no clue why the dot is added in the gurmukhi version
- 1st is half ṣ (typed as ष् + char), 2nd one is half ś (typed as श् + char)
- The conjunct for kṣa (क् + ष = क्ष)
- Half kṣa (typed as क्ष् + char)
- The conjunct for jña (ज् + ञ = ज्ञ)
- Half r (typed as र् + char). This is not pairin-rara in punjabi, which comes after the consonant, instead this is a half-r preceding the conjunct, even though it is written at the far top right of the conjunct, it is pronounced initially in the cluster.
- Addak Bindi. This exists in Gurmukhi already. However, in Sant Lipi it is specifically being used to produce a bindi before bihari. Either have to change that strategy, or need to use Devanagari Addak Bindi whenever it is needed in Gurmukhi (aside from Mahan Kosh, I have zero examples except obscure and niche old dictionaries, whose legitimacy I haven't researched/looked into, but regardless could also be satisifed with Devanagari Addak Bindi U+0901, [Chandrabindu](https://en.wikipedia.org/wiki/Chandrabindu)).
- Half m (typed ੍ + ਮ = ੍ਮ). This already exists in Unicode fonts today, it is already in Sant Lipi as well. I don't know if this is being used at the beginning of a word, in which case we may need to evaluate the impact of showing the dotted circle at the start (as this is meant to be used non-initially).
- Independent form of vocalic r (r̥  = U+090B), basically extinct today

Notes (going down column 2)

This seems even harder to integrate into the font. Will have to investigate further.

- ṣâd (U+0635)
- s̱e (U+062B)
- ẕâl (U+0630)
- že (U+0698)
- zâd (U+0636)
- ẓâ (U+0638)
- ʿayn (U+0639)
- ġayn (U+063A)
- fe (U+0641)
- qâf (U+0642)
- xe (U+062E)
- ze (U+0632)

The most likely approach will be to add ligatures with control chars for Gurmukhi. The same way we use addak bindi for bindi-before-bihari. Or the way we use north-indic fraction chars to vary yayyas. Will have a play around and see what works.

**Comment by dsomel21** [comment]
BTW, how are you looking up the number of instances in Mahan Kosh?

**Comment by bhajneet** [comment]
If you search the character in the PDF, it shows the number of results. You can find a PDF of Mahan Kosh with a quick google search.

**Comment by bhajneet** [comment]
Print of Mahan Kosh that I have at home:

![8EA3A7FF-03EA-48C3-94D1-2CCE6D295D68_1_201_a](https://github.com/shabados/SantLipi/assets/14130567/edd443ef-b28c-4a03-bc4c-21eca9d0153f)
